# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Rj5MX1QJula1icVAR_kdITC3VorT9tze
"""

from google.colab import files
data_to_load = files.upload()

import pandas as pd 
import io
import numpy as np

df_train = pd.read_csv(io.BytesIO(data_to_load['_imu_data.csv']))
df_train
print(df_train.iloc[:,[1]])
tab=np.array(df_train.iloc[:,[1]])



for i in range(1,len(tab)-1):
  tab[i][0]=(abs(tab[i-1][0])+abs(tab[i][0])+abs(tab[i+1][0]))/3
tab[0][0]=(abs(tab[0][0])+abs(tab[1][0]))/2
tab[len(tab)-1][0]=(abs(tab[len(tab)-1][0])+abs(tab[len(tab)-2][0]))/2
print(tab)
#print(tab[940])
df_train['y']=tab
df_train
df_train.to_csv("imu.csv", index=False)

